/** Menu from Ivaan Foods restaurant PDF (prices as on menu). */

export type SeedItem = { name: string; price: number };

export type SeedCategory = { name: string; items: SeedItem[] };

export const MENU_SEED: SeedCategory[] = [
  {
    name: "Coffee & Chai",
    items: [
      { name: "Ginger Tea", price: 20 },
      { name: "Coffee", price: 30 },
      { name: "Elaichi Tea", price: 25 },
      { name: "Masala Tea", price: 25 },
      { name: "Black Tea", price: 15 },
      { name: "Lemon Tea", price: 20 },
      { name: "Ginger Honey Lemon", price: 50 },
      { name: "Lemon Grass Tea", price: 50 },
      { name: "Tulsi Ginger Tea", price: 50 },
      { name: "Mint Tea", price: 50 },
      { name: "Gur Tea", price: 30 },
      { name: "Tulsi Mulethi Tea", price: 50 },
      { name: "Vanilla Coffee", price: 50 },
      { name: "Black Coffee", price: 30 },
      { name: "Green Tea", price: 50 },
    ],
  },
  {
    name: "Sandwiches",
    items: [
      { name: "Plain Sandwich", price: 70 },
      { name: "Cheese Sandwich", price: 100 },
      { name: "Cheese Paneer Sandwich", price: 120 },
      { name: "Paneer Sandwich", price: 140 },
      { name: "Masala Sandwich", price: 90 },
      { name: "Peri Peri Sandwich", price: 90 },
      { name: "Peri Peri Cheese Sandwich", price: 110 },
    ],
  },
  {
    name: "Burger",
    items: [
      { name: "Classic Burger", price: 70 },
      { name: "Cheese Burger", price: 90 },
      { name: "Paneer Burger", price: 110 },
      { name: "Chilli Paneer Burger", price: 150 },
      { name: "Crispy Paneer Burger", price: 150 },
    ],
  },
  {
    name: "Breakfast & Maggi",
    items: [
      { name: "Poha", price: 80 },
      { name: "Vada Pao", price: 40 },
      { name: "Plain Maggi", price: 50 },
      { name: "Veg Maggi", price: 60 },
      { name: "Cheese Maggi", price: 80 },
      { name: "Garlic Cheese Maggi", price: 100 },
      { name: "Ivaan's Special Maggi", price: 120 },
      { name: "Egg Maggi", price: 100 },
      { name: "Chilla (2 Pcs.)", price: 30 },
      { name: "Egg Bhurji", price: 70 },
      { name: "Bread Toast", price: 40 },
      { name: "Boiled Egg", price: 30 },
      { name: "Double Egg Omelette", price: 60 },
      { name: "Half Fry", price: 35 },
      { name: "Egg Fry", price: 35 },
    ],
  },
  {
    name: "Pakode & Snacks",
    items: [
      { name: "Aloo Pakode", price: 70 },
      { name: "Onion Pakode", price: 70 },
      { name: "Bread Pakode", price: 50 },
      { name: "Paneer Pakode", price: 90 },
      { name: "Samosa", price: 20 },
      { name: "Aloo Patties", price: 30 },
      { name: "Paneer Patties", price: 50 },
      { name: "Ivaan Paneer Patties", price: 80 },
      { name: "Bhel Puri", price: 50 },
      { name: "Chole Samosa", price: 50 },
    ],
  },
  {
    name: "South Indian",
    items: [
      { name: "Plain Dosa", price: 80 },
      { name: "Masala Dosa", price: 120 },
      { name: "Onion Dosa", price: 120 },
      { name: "Veg Creamy Dosa", price: 150 },
      { name: "Masala Idli", price: 80 },
      { name: "Plain Idli (2 Pcs.)", price: 60 },
      { name: "Uthappam", price: 65 },
    ],
  },
  {
    name: "Pasta",
    items: [
      { name: "White Sauce Pasta", price: 150 },
      { name: "Red Sauce Pasta", price: 150 },
      { name: "Plain Pasta / Macaroni", price: 100 },
      { name: "Makhani Pasta", price: 200 },
    ],
  },
  {
    name: "Chinese Starters",
    items: [
      { name: "Honey Chilli Potato", price: 160 },
      { name: "Chilli Paneer", price: 190 },
      { name: "Paneer 65", price: 200 },
      { name: "Veg Manchurian Dry", price: 150 },
      { name: "Veg Manchurian Gravy", price: 170 },
      { name: "Chilli Potato", price: 150 },
      { name: "Chilli Mushroom", price: 180 },
      { name: "Crispy Mushroom", price: 160 },
      { name: "Crispy Corn", price: 120 },
      { name: "Paneer Manchurian Dry", price: 190 },
      { name: "Paneer Manchurian Gravy", price: 220 },
      { name: "Golden Fried Baby Corn", price: 160 },
      { name: "Baby Corn Manchurian", price: 160 },
      { name: "Baby Corn Chilli", price: 140 },
      { name: "Baby Corn Crispy", price: 140 },
    ],
  },
  {
    name: "French Fries",
    items: [
      { name: "French Fries", price: 90 },
      { name: "Peri Peri French Fries", price: 120 },
      { name: "Salted Fries", price: 90 },
      { name: "BBQ Fries", price: 120 },
      { name: "American Creamy & Onion Fries", price: 120 },
    ],
  },
  {
    name: "Fried Rice",
    items: [
      { name: "Egg Fried Rice", price: 150 },
      { name: "Chilli Garlic Fried Rice", price: 120 },
      { name: "Mixed Fried Rice", price: 160 },
      { name: "Veg Fried Rice", price: 100 },
      { name: "Schezwan Fried Rice", price: 120 },
      { name: "Paneer Fried Rice", price: 140 },
      { name: "Mushroom Fried Rice", price: 170 },
    ],
  },
  {
    name: "Momo (8 pcs)",
    items: [
      { name: "Steam Momo", price: 80 },
      { name: "Fried Momo", price: 80 },
      { name: "Peri Peri Momo", price: 120 },
      { name: "Chilli Momo", price: 140 },
      { name: "Kurkure Momo", price: 150 },
      { name: "Schezwan Momo", price: 140 },
      { name: "Manchurian Momo", price: 140 },
      { name: "Pizza Momo", price: 200 },
      { name: "Cheese Corn Momo", price: 200 },
    ],
  },
  {
    name: "Quick Lunch",
    items: [
      { name: "Sambar Rice / Dal Rice", price: 100 },
      { name: "Chole Rice", price: 100 },
      { name: "Rajma Rice", price: 100 },
      { name: "Kadhi Rice", price: 100 },
      { name: "Paneer Rice", price: 150 },
    ],
  },
  {
    name: "Main Course",
    items: [
      { name: "Paneer Butter Masala", price: 240 },
      { name: "Paneer Do Pyaza", price: 240 },
      { name: "Jeera Aloo", price: 80 },
      { name: "Mix Veg", price: 120 },
      { name: "Yellow Dal Tadka", price: 80 },
      { name: "Yellow Dal Fry", price: 100 },
      { name: "Dal Makhani", price: 150 },
      { name: "Kadai Paneer", price: 220 },
      { name: "Chole Masala", price: 120 },
      { name: "Rajma Masala", price: 120 },
      { name: "Egg Curry", price: 150 },
      { name: "Chole Bhature (2 pcs)", price: 100 },
      { name: "Puri Bhaji (4 pcs)", price: 80 },
    ],
  },
  {
    name: "Rice",
    items: [
      { name: "Jeera Rice", price: 100 },
      { name: "Veg Pulao", price: 120 },
      { name: "Peas Pulao", price: 150 },
      { name: "Veg Biryani", price: 180 },
      { name: "Steamed Rice", price: 80 },
    ],
  },
  {
    name: "Indian Breads",
    items: [
      { name: "Tawa Roti", price: 10 },
      { name: "Plain Paratha", price: 50 },
      { name: "Aloo Paratha", price: 70 },
      { name: "Onion Paratha", price: 70 },
      { name: "Gobhi Paratha", price: 70 },
      { name: "Paneer Paratha", price: 90 },
      { name: "Mix Veg Paratha", price: 100 },
      { name: "Cheese Paratha", price: 120 },
      { name: "Aloo Onion Paratha", price: 80 },
    ],
  },
  {
    name: "Noodles",
    items: [
      { name: "Veg Hakka Noodles", price: 170 },
      { name: "Paneer Hakka Noodles", price: 190 },
      { name: "Egg Noodles", price: 160 },
      { name: "Schezwan Noodles", price: 160 },
      { name: "Veg Noodles", price: 100 },
      { name: "Paneer Noodles", price: 140 },
      { name: "Chilli Garlic Noodles", price: 120 },
      { name: "Chilli Garlic Paneer Noodles", price: 150 },
    ],
  },
  {
    name: "Rolls",
    items: [
      { name: "Chilli Paneer Roll", price: 150 },
      { name: "Double Egg Roll", price: 120 },
      { name: "Schezwan Paneer Roll", price: 160 },
      { name: "Noodles Roll", price: 100 },
      { name: "Veg Roll", price: 80 },
      { name: "Paneer Roll", price: 100 },
      { name: "Veg Cheese Roll", price: 130 },
      { name: "Paneer Cheese Roll", price: 150 },
    ],
  },
  {
    name: "Pizza & Kulche",
    items: [
      { name: "Paneer Cheese Pizza", price: 120 },
      { name: "Peri Peri Bread Pizza", price: 99 },
      { name: "Corn Pizza", price: 100 },
      { name: "Pasta Pizza", price: 250 },
      { name: "Chole Kulche (2 pcs)", price: 80 },
    ],
  },
  {
    name: "Thali & Biryani",
    items: [
      { name: "Veg Thali", price: 160 },
      { name: "Veg Thali Super Deluxe", price: 180 },
      { name: "Shahi Paneer Thali", price: 200 },
      { name: "Kadhai Paneer Thali", price: 200 },
      { name: "Dal Makhani Thali", price: 200 },
      { name: "Dum Biryani", price: 120 },
      { name: "Veg Biryani (Thali style)", price: 100 },
      { name: "Chef's Special Biryani", price: 140 },
    ],
  },
  {
    name: "Office Combo",
    items: [
      { name: "Paneer Lababdar + 4 Roti", price: 150 },
      { name: "Shahi Paneer + 4 Roti", price: 150 },
      { name: "Matar Paneer + 4 Roti", price: 150 },
      { name: "Kadhai Paneer + 4 Roti", price: 150 },
      { name: "Veg Noodles + Chilli Paneer + Coke", price: 200 },
      { name: "Veg Fried Rice + Chilli Paneer + Coke", price: 250 },
    ],
  },
  {
    name: "Shakes",
    items: [
      { name: "Banana Dates Shake", price: 80 },
      { name: "Oreo Shake", price: 100 },
      { name: "Kit Kat Shake", price: 100 },
      { name: "Banana Shake", price: 70 },
      { name: "Peanut Banana Shake", price: 70 },
      { name: "Mango Shake", price: 90 },
    ],
  },
  {
    name: "Mocktails",
    items: [
      { name: "Watermelon Mojito", price: 100 },
      { name: "Strawberry Mojito", price: 100 },
      { name: "Blue Lagoon", price: 100 },
      { name: "Virgin Mojito", price: 100 },
    ],
  },
  {
    name: "Chaat Specials",
    items: [
      { name: "Chaat Basket", price: 100 },
      { name: "Corn Chaat", price: 100 },
      { name: "Cheese Chaat Basket", price: 120 },
      { name: "Peanut Chaat", price: 100 },
      { name: "Veg Tikki Chaat", price: 150 },
    ],
  },
  {
    name: "Lassi & Drinks",
    items: [
      { name: "Salted Lassi", price: 80 },
      { name: "Pineapple Lassi", price: 80 },
      { name: "Strawberry Lassi", price: 80 },
      { name: "Sweet Lassi", price: 80 },
      { name: "Mango Lassi", price: 80 },
      { name: "Butter Scotch Lassi", price: 80 },
      { name: "Nimbu Pani", price: 40 },
      { name: "Masala Soda", price: 60 },
      { name: "Lemon Soda", price: 50 },
    ],
  },
];
